apiVersion: "v1"
kind: Service
metadata:
  name: "solrcloud-appliance"
  namespace: "example"
spec:
  selector:
    application: "solrcloud-appliance"
  ports:
    - protocol: "TCP"
      port: 8983
      targetPort: 8983
      name: solr
